version: '3.3'

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db


networks:
    inception:
        driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart:  on-failure

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/

  adminer:
    container_name: adminer
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  prometheus:
    container_name: prometheus
    build: 
      context: .
      dockerfile: requirements/bonus/prometheus/Dockerfile
    ports:
      - 9090:9090
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    build: 
      context: .
      dockerfile: requirements/bonus/ftp/Dockerfile
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000:21000"
    volumes:
      - wp-volume:/home/gtaggana/ftp/files
    networks:
      - inception
    restart: always

  website:
    container_name: website
    build:
      context: .
      dockerfile: requirements/bonus/site/Dockerfile
    ports:
      - "8081:8081"
    restart: always
